# Generated by Django 3.2.8 on 2021-11-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('imagePath', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('distance', models.IntegerField(blank=True, default=0)),
                ('postedBy', models.CharField(max_length=40)),
                ('updatedBy', models.CharField(max_length=40)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateOn', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='New', max_length=10)),
                ('notes', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
