# Generated by Django 3.2.8 on 2021-11-18 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ps', '0002_plantdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(default='', max_length=200)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('lastUpdateOn', models.DateTimeField(auto_now=True)),
                ('updatedBy', models.CharField(max_length=20)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.plantdetails')),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
